/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Image from "next/image";
import { useSignInWithGoogle } from "react-firebase-hooks/auth";
import { auth } from "../firebase";

const Login = () => {
  const [signInWithGoogle, userCred, loading, error] =
    useSignInWithGoogle(auth);

  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
        <title>Google Docs Login</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn-icons-png.flaticon.com/512/5968/5968517.png"
        />
      </Head>
      <Image
        src="https://i.postimg.cc/SRjV6PgT/google-Doc-Logo.png"
        objectFit="contain"
        height="300"
        width="550"
      />
      <button
        onClick={() => signInWithGoogle()}
        type="button"
        data-mdb-ripple="true"
        data-mdb-ripple-color="light"
        className="inline-block w-44 mt-10 px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
      >
        Login
      </button>
    </div>
  );
};

export default Login;
