/* eslint-disable @next/next/no-img-element */
/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable react-hooks/exhaustive-deps */
import DescriptionIcon from "@mui/icons-material/Description";
import GroupIcon from "@mui/icons-material/Group";
import "firebase/compat/auth";
import "firebase/compat/firestore";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { useAuthState } from "react-firebase-hooks/auth";
import TextEditor from "../../components/TextEditor";
import db, { auth } from "../../firebase";

const Doc = () => {
  const [user] = useAuthState(auth);
  /* if (!user) return <Login />; */
  const router = useRouter();
  const { id } = router.query;
  const [messages, setMessages] = useState([]);

  useEffect(() => {
    db.collection("userDocs")
      .doc(user?.email)
      .collection("docs")
      .onSnapshot((snapshot) =>
        snapshot.docs.map((doc) => {
          if (doc.id === id) {
            setMessages(doc.data());
          }
        })
      );
  }, [db, id, user?.email]);

  return (
    <div>
      <Head>
        <title>Google Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn-icons-png.flaticon.com/512/5968/5968517.png"
        />
      </Head>
      <header className="flex justify-between items-center p-3 pb-1">
        <span onClick={() => router.push("/")} className="cursor-pointer">
          <DescriptionIcon
            className="text-blue-500"
            style={{ fontSize: "3rem" }}
          />
        </span>
        <div className="flex-grow px-2">
          <h2>{messages.fileName}</h2>
          <div
            className="flex items-center text-sm space-x-1 -ml-1 h-8
          text-gray-600"
          >
            <p className="option">File</p>
            <p className="option">Edit</p>
            <p className="option">View</p>
            <p className="option">Insert</p>
            <p className="option">Format</p>
            <p className="option">Tools</p>
          </div>
        </div>

        <button className="hidden md:inline-block w-32 px-6 py-2.5 bg-blue-700 text-white font-medium text-sm leading-tight rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-200 active:shadow-lg transition duration-150 ease-in-out">
          <GroupIcon className="text-white" /> SHARE
        </button>
        <img
          className="rounded-full cursor-pointer 
        h-10 w-10 ml-2"
          src={user?.photoURL}
          alt=""
        />
      </header>
      <TextEditor />
    </div>
  );
};

export default Doc;
